import { TIME } from "./time";

export const ACCESS_TOKEN_NAME = "REALMS_AUTH_TOKEN";
export const ACCESS_TOKEN_SECRET =
	"eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0Mjg0ODk5MCwiaWF0IjoxNjQyODQ4OTkwfQ.z5rPyt43KkHUHeI0h6hHTsaMZN2_KIC3T7DQrObNRxs";
export const ACCESS_TOKEN_MAX_AGE = TIME.HOUR * 8;
export const ACCESS_TOKEN_EXPIRY_DATE = new Date(Date.now() + ACCESS_TOKEN_MAX_AGE * 1000);

// export const REFRESH_TOKEN_NAME = 'REALMS_REFRESH_TOKEN';
// export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
// export const REFRESH_TOKEN_MAX_AGE = TIME.WEEK;
